### PR TITLE
[close #206]Fix no suitable driver found for jdbc

### LINKED ISSUE #206: [BUG] Flink 1.14: No suitable driver found for jdbc url
**Describe the bug**

When I try to compile flink-1.14 into a jar and use it in SQL-Flink client, I met a mistake.

**What did you do**

1. compile
```
mvn clean package -DskipTests -am -pl flink/flink-1.14 -Ddep.flink.version=1.14.4 -Dmysql.driver.scope=compile -Dflink.jdbc.connector.scope=compile -Dflink.kafka.connector.scope=compile
```
2. cp to Flink/lib
```
cp ${TIBIGDATA_HOME}/flink/flink-1.14/target/flink-tidb-connector-1.14-${TIBIGDATA_VERSION}.jar lib
```

3. run
```
cd ~/Flink/
bin/sql-client.sh
Flink SQL> CREATE CATALOG `tidb2`
> WITH (
>     'type' = 'tidb',
>     'tidb.database.url' = 'jdbc:mysql://127.0.0.1:4000/tispark_test',
>     'tidb.username' = 'root',
>     'tidb.password' = '',
> );
[ERROR] Could not execute SQL statement. Reason:
java.sql.SQLException: No suitable driver found for jdbc:mysql://127.0.0.1:4000/tispark_test
```

**What do you expect**

```
Flink SQL> CREATE CATALOG `tidb2`
> WITH (
>     'type' = 'tidb',
>     'tidb.database.url' = 'jdbc:mysql://127.0.0.1:4000/tispark_test',
>     'tidb.username' = 'root',
>     'tidb.password' = '',
> );
[INFO] Execute statement succeed.

```

**What happens instead**

Here is error stack.
```
Could not execute SQL statement.
org.apache.flink.table.client.gateway.SqlExecutionException: Could not execute SQL statement.
	at org.apache.flink.table.client.gateway.local.LocalExecutor.executeOperation(LocalExecutor.java:211) ~[flink-sql-client_2.12-1.14.4.jar:1.14.4]
	at org.apache.flink.table.client.cli.CliClient.executeOperation(CliClient.java:625) ~[flink-sql-client_2.12-1.14.4.jar:1.14.4]
	at org.apache.flink.table.client.cli.CliClient.callOperation(CliClient.java:447) ~[flink-sql-client_2.12-1.14.4.jar:1.14.4]
	at org.apache.flink.table.client.cli.CliClient.lambda$executeStatement$1(CliClient.java:332) [flink-sql-client_2.12-1.14.4.jar:1.14.4]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_332]
	at org.apache.flink.table.client.cli.CliClient.executeStatement(CliClient.java:325) [flink-sql-client_2.12-1.14.4.jar:1.14.4]
	at org.apache.flink.table.client.cli.CliClient.executeInteractive(CliClient.java:297) [flink-sql-client_2.12-1.14.4.jar:1.14.4]
	at org.apache.flink.table.client.cli.CliClient.executeInInteractiveMode(CliClient.java:221) [flink-sql-client_2.12-1.14.4.jar:1.14.4]
	at org.apache.flink.table.client.SqlClient.openCli(SqlClient.java:151) [flink-sql-client_2.12-1.14.4.jar:1.14.4]
	at org.apache.flink.table.client.SqlClient.start(SqlClient.java:95) [flink-sql-client_2.12-1.14.4.jar:1.14.4]
	at org.apache.flink.table.client.SqlClient.startClient(SqlClient.java:187) [flink-sql-client_2.12-1.14.4.jar:1.14.4]
	at org.apache.flink.table.client.SqlClient.main(SqlClient.java:161) [flink-sql-client_2.12-1.14.4.jar:1.14.4]
Caused by: org.apache.flink.table.api.ValidationException: Could not execute CREATE CATALOG: (catalogName: [tidb2], properties: [{tidb.password=, tidb.username=root, tidb.cluster-jks-trust-path=/config/cert/jks/server-cert-store, tidb.cluster-jks-enable=true, type=tidb, tidb.cluster-jks-trust-password=12345678, tidb.cluster-tls-enable=true, tidb.cluster-jks-key-path=/config/cert/jks/client-keystore, tidb.database.url=jdbc:mysql://127.0.0.1:4000/tispark_test, tidb.cluster-jks-key-password=123456}])
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.createCatalog(TableEnvironmentImpl.java:1301) ~[flink-table_2.12-1.14.4.jar:1.14.4]
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeInternal(TableEnvironmentImpl.java:1122) ~[flink-table_2.12-1.14.4.jar:1.14.4]
	at org.apache.flink.table.client.gateway.local.LocalExecutor.lambda$executeOperation$3(LocalExecutor.java:209) ~[flink-sql-client_2.12-1.14.4.jar:1.14.4]
	at org.apache.flink.table.client.gateway.context.ExecutionContext.wrapClassLoader(ExecutionContext.java:88) ~[flink-sql-client_2.12-1.14.4.jar:1.14.4]
	at org.apache.flink.table.client.gateway.local.LocalExecutor.executeOperation(LocalExecutor.java:209) ~[flink-sql-client_2.12-1.14.4.jar:1.14.4]
	... 11 more
Caused by: org.apache.flink.table.catalog.exceptions.CatalogException: Can not init client session
	at io.tidb.bigdata.flink.connector.TiDBCatalog.initClientSession(TiDBCatalog.java:107) ~[flink-tidb-connector-1.14-0.0.5-SNAPSHOT.jar:?]
	at io.tidb.bigdata.flink.connector.TiDBCatalog.open(TiDBCatalog.java:115) ~[flink-tidb-connector-1.14-0.0.5-SNAPSHOT.jar:?]
	at org.apache.flink.table.catalog.CatalogManager.registerCatalog(CatalogManager.java:195) ~[flink-table_2.12-1.14.4.jar:1.14.4]
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.createCatalog(TableEnvironmentImpl.java:1297) ~[flink-table_2.12-1.14.4.jar:1.14.4]
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeInternal(TableEnvironmentImpl.java:1122) ~[flink-table_2.12-1.14.4.jar:1.14.4]
	at org.apache.flink.table.client.gateway.local.LocalExecutor.lambda$executeOperation$3(LocalExecutor.java:209) ~[flink-sql-client_2.12-1.14.4.jar:1.14.4]
	at org.apache.flink.table.client.gateway.context.ExecutionContext.wrapClassLoader(ExecutionContext.java:88) ~[flink-sql-client_2.12-1.14.4.jar:1.14.4]
	at org.apache.flink.table.client.gateway.local.LocalExecutor.executeOperation(LocalExecutor.java:209) ~[flink-sql-client_2.12-1.14.4.jar:1.14.4]
	... 11 more
Caused by: java.lang.IllegalStateException: can not get pdAddresses
	at io.tidb.bigdata.tidb.ClientSession.loadPdAddresses(ClientSession.java:320) ~[flink-tidb-connector-1.14-0.0.5-SNAPSHOT.jar:?]
	at io.tidb.bigdata.tidb.ClientSession.<init>(ClientSession.java:103) ~[flink-tidb-connector-1.14-0.0.5-SNAPSHOT.jar:?]
	at io.tidb.bigdata.tidb.ClientSession.create(ClientSession.java:589) ~[flink-tidb-connector-1.14-0.0.5-SNAPSHOT.jar:?]
	at io.tidb.bigdata.flink.connector.TiDBCatalog.initClientSession(TiDBCatalog.java:105) ~[flink-tidb-connector-1.14-0.0.5-SNAPSHOT.jar:?]
	at io.tidb.bigdata.flink.connector.TiDBCatalog.open(TiDBCatalog.java:115) ~[flink-tidb-connector-1.14-0.0.5-SNAPSHOT.jar:?]
	at org.apache.flink.table.catalog.CatalogManager.registerCatalog(CatalogManager.java:195) ~[flink-table_2.12-1.14.4.jar:1.14.4]
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.createCatalog(TableEnvironmentImpl.java:1297) ~[flink-table_2.12-1.14.4.jar:1.14.4]
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeInternal(TableEnvironmentImpl.java:1122) ~[flink-table_2.12-1.14.4.jar:1.14.4]
	at org.apache.flink.table.client.gateway.local.LocalExecutor.lambda$executeOperation$3(LocalExecutor.java:209) ~[flink-sql-client_2.12-1.14.4.jar:1.14.4]
	at org.apache.flink.table.client.gateway.context.ExecutionContext.wrapClassLoader(ExecutionContext.java:88) ~[flink-sql-client_2.12-1.14.4.jar:1.14.4]
	at org.apache.flink.table.client.gateway.local.LocalExecutor.executeOperation(LocalExecutor.java:209) ~[flink-sql-client_2.12-1.14.4.jar:1.14.4]
	... 11 more
Caused by: java.sql.SQLException: No suitable driver found for jdbc:mysql://127.0.0.1:4000/tispark_test
	at java.sql.DriverManager.getConnection(DriverManager.java:689) ~[?:1.8.0_332]
	at java.sql.DriverManager.getConnection(DriverManager.java:247) ~[?:1.8.0_332]
	at io.tidb.bigdata.tidb.JdbcConnectionProviderFactory$BasicJdbcConnectionProvider.getConnection(JdbcConnectionProviderFactory.java:62) ~[flink-tidb-connector-1.14-0.0.5-SNAPSHOT.jar:?]
	at io.tidb.bigdata.tidb.ClientSession.loadPdAddresses(ClientSession.java:311) ~[flink-tidb-connector-1.14-0.0.5-SNAPSHOT.jar:?]
	at io.tidb.bigdata.tidb.ClientSession.<init>(ClientSession.java:103) ~[flink-tidb-connector-1.14-0.0.5-SNAPSHOT.jar:?]
	at io.tidb.bigdata.tidb.ClientSession.create(ClientSession.java:589) ~[flink-tidb-connector-1.14-0.0.5-SNAPSHOT.jar:?]
	at io.tidb.bigdata.flink.connector.TiDBCatalog.initClientSession(TiDBCatalog.java:105) ~[flink-tidb-connector-1.14-0.0.5-SNAPSHOT.jar:?]
	at io.tidb.bigdata.flink.connector.TiDBCatalog.open(TiDBCatalog.java:115) ~[flink-tidb-connector-1.14-0.0.5-SNAPSHOT.jar:?]
	at org.apache.flink.table.catalog.CatalogManager.registerCatalog(CatalogManager.java:195) ~[flink-table_2.12-1.14.4.jar:1.14.4]
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.createCatalog(TableEnvironmentImpl.java:1297) ~[flink-table_2.12-1.14.4.jar:1.14.4]
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeInternal(TableEnvironmentImpl.java:1122) ~[flink-table_2.12-1.14.4.jar:1.14.4]
	at org.apache.flink.table.client.gateway.local.LocalExecutor.lambda$executeOperation$3(LocalExecutor.java:209) ~[flink-sql-client_2.12-1.14.4.jar:1.14.4]
	at org.apache.flink.table.client.gateway.context.ExecutionContext.wrapClassLoader(ExecutionContext.java:88) ~[flink-sql-client_2.12-1.14.4.jar:1.14.4]
	at org.apache.flink.table.client.gateway.local.LocalExecutor.executeOperation(LocalExecutor.java:209) ~[flink-sql-client_2.12-1.14.4.jar:1.14.4]
	... 11 more
```

**Flink and TiBigData version info**
- Flink version: 1.14.4
- TiBigData Flink version: 1.14

### PR DESCRIPTION
**Pull request by Daemonxiao**
## What is the purpose of the change

To fix #206。

## Brief change log
Register the JDBC driver before building a connection.

## Verifying this change
This change added tests and can be verified as follows:
1. compile TiBigData Flink-1.14
```
$ mvn clean install -DskipTests -am -pl flink/flink-1.14 -Ddep.flink.version=1.14.4 -Dmysql.driver.scope=compile -Dflink.jdbc.connector.scope=compile -Dflink.kafka.connector.scope=compile
```

2. copy to flink/lib
```
$ cp ~/IdeaProject/TiBigData/flink/flink-1.14/target/flink-tidb-connector-1.14-0.0.5-SNAPSHOT.jar ~/flink/lib
```

3. test
```
$ bin/sql-client.sh 
Flink SQL> CREATE CATALOG `tidb2\`
> WITH (
>     'type' = 'tidb',
>     'tidb.database.url' = 'jdbc:mysql://127.0.0.1:4000/test',
>     'tidb.username' = 'root',
>     'tidb.password' = '',
>     'tidb.cluster-tls-enable' = 'true',
>     'tidb.cluster-jks-enable' = 'true',
>     'tidb.cluster-jks-key-path' = '/config/cert/jks/client-keystore',
>     'tidb.cluster-jks-key-password' = '123456',
>     'tidb.cluster-jks-trust-path' = '/config/cert/jks/server-cert-store',
>     'tidb.cluster-jks-trust-password' = '12345678'
> );
[INFO] Execute statement succeed.
``` 

## Does this pull request potentially affect one of the following parts:

- Dependencies (does it add or upgrade a dependency): (no)
- The public API: (no)
- The runtime per-record code paths (performance sensitive): (no)

## Documentation

- Does this pull request introduce a new feature? ( no)

### The Reson of #206 
Because the h2database is used in flink-connector-jdbc_2.11, it change the `META-INF/.services/java.sql.Driver` in the flink-tidb-connector-1.14. We can see the content is `org.h2.Driver` that would be initialized in loadInitialDrivers() that makes no suitable driver for jdbc://mysqlXXX.
JI1ZHgSbV0
uFBlkOG7b7

### How to register a driver for JDBC?
There are two simple ways to complete it.
- Code: `Class.forName("xxxx")`
- Add driver class in META-INF/services/java.sql.Driver file

Here is a JAVA [DriverManager usage](https://docs.oracle.com/javase/8/docs/api/java/sql/DriverManager.html).

### CODE REVIEW

File: tidb/src/main/java/io/tidb/bigdata/tidb/JdbcConnectionProviderFactory.java [hunk 1]
```diff
@@ -28,6 +28,7 @@ public class JdbcConnectionProviderFactory {
 
   public static JdbcConnectionProvider createJdbcConnectionProvider(ClientConfig config) {
     try {
+      Class.forName(ClientConfig.MYSQL_DRIVER_NAME);
```
Comment (xuanyu66) [inline tidb/src/main/java/io/tidb/bigdata/tidb/JdbcConnectionProviderFactory.java:31]: What's the purpose

**Review by xuanyu66 — CHANGES_REQUESTED** [review]
The change log says to fix the bug by registering the JDBC driver.
Can you explain how to register and the principle of it

File: tidb/src/main/java/io/tidb/bigdata/tidb/JdbcConnectionProviderFactory.java (hunk 1 above)
Comment (Daemonxiao) [reply tidb/src/main/java/io/tidb/bigdata/tidb/JdbcConnectionProviderFactory.java:31]: It is a static function in com.mysql.jdbc.driver that register the MySQL driver to JAVA driver manager.
7f2pLCJXJl
Here is a link about [register driver](https://stackoverflow.com/questions/9575367/about-jdbc-drivers).

Comment (Daemonxiao) [reply tidb/src/main/java/io/tidb/bigdata/tidb/JdbcConnectionProviderFactory.java:31]: You can click to find an [official description of DriverManager](https://docs.oracle.com/javase/8/docs/api/java/sql/DriverManager.html).

Comment (xuanyu66) [reply tidb/src/main/java/io/tidb/bigdata/tidb/JdbcConnectionProviderFactory.java:31]: Add a comment, load class will cause the driver to register itself to DriverMananger

Comment (Daemonxiao) [reply tidb/src/main/java/io/tidb/bigdata/tidb/JdbcConnectionProviderFactory.java:32]: OK, I have added a comment to explain the `Class.forName(JDBC_Driver)`.

Comment (shiyuhang0) [reply tidb/src/main/java/io/tidb/bigdata/tidb/JdbcConnectionProviderFactory.java:32]: if we don't register JDBC driver, it will register h2 driver in default?

File: flink/flink-1.14/src/main/java/io/tidb/bigdata/flink/connector/utils/JdbcUtils.java [hunk 2]
```diff
@@ -59,7 +57,7 @@ public static JdbcConnectorOptions getJdbcOptions(Map<String, String> properties
         dbUrl.matches("jdbc:(mysql|tidb)://[^/]+:\\d+/.*"),
         "the format of database url does not match jdbc:(mysql|tidb)://host:port/.*");
     dbUrl = rewriteJdbcUrlPath(dbUrl, databaseName);
-    String driverName = dbUrl.startsWith(TIDB_URL_PREFIX) ? TIDB_DRIVER_NAME : MYSQL_DRIVER_NAME;
+    String driverName = TiDBDriver.driverForUrl(dbUrl);
```
Comment (shiyuhang0) [inline flink/flink-1.14/src/main/java/io/tidb/bigdata/flink/connector/utils/JdbcUtils.java:60]: can you introduce what is the difference of jdbc:mysql and jdbc:tidb

File: tidb/src/main/java/io/tidb/bigdata/tidb/JdbcConnectionProviderFactory.java [hunk 3]
```diff
@@ -28,6 +28,8 @@ public class JdbcConnectionProviderFactory {
 
   public static JdbcConnectionProvider createJdbcConnectionProvider(ClientConfig config) {
     try {
+      // load JDBC drivers and register to DriverManager
+      Class.forName(ClientConfig.MYSQL_DRIVER_NAME);
       Class<?> provideClass = Class.forName(config.getJdbcConnectionProviderImpl());
```
Comment (shiyuhang0) [inline tidb/src/main/java/io/tidb/bigdata/tidb/JdbcConnectionProviderFactory.java:33]: can you introduce what's the purpose of this forname

File: flink/flink-1.14/src/main/java/io/tidb/bigdata/flink/connector/utils/JdbcUtils.java (hunk 2 above)
Comment (Daemonxiao) [reply flink/flink-1.14/src/main/java/io/tidb/bigdata/flink/connector/utils/JdbcUtils.java:60]: `jdbc:tidb` is used for TiDB-connector that you can find in TiBigData/jdbc. It is the exclusive connector for TiDB.
Because TiDB is compatible with MySQL and can use MySQL-connector, we can also use `jdbc:mysql`.
Btw, TiDB-connector is a wrapper of MySQL-connector in fact.

File: tidb/src/main/java/io/tidb/bigdata/tidb/JdbcConnectionProviderFactory.java (hunk 1 above)
Comment (Daemonxiao) [reply tidb/src/main/java/io/tidb/bigdata/tidb/JdbcConnectionProviderFactory.java:32]: @shiyuhang0 Now, DriverManager would find the JDBC class name in `META-INF/services/java.sql.Driver` file. It will register h2db auto.

Comment (xuanyu66) [reply tidb/src/main/java/io/tidb/bigdata/tidb/JdbcConnectionProviderFactory.java]: Please add the method link, otherwise, it's still difficult to understand how to register

File: tidb/src/main/java/io/tidb/bigdata/tidb/JdbcConnectionProviderFactory.java [hunk 4]
```diff
@@ -28,6 +28,8 @@ public class JdbcConnectionProviderFactory {
 
   public static JdbcConnectionProvider createJdbcConnectionProvider(ClientConfig config) {
     try {
+      // load JDBC drivers and register to DriverManager
+      Class.forName(ClientConfig.MYSQL_DRIVER_NAME);
```
[the remark this answers is not in the document]
Comment (Daemonxiao) [reply tidb/src/main/java/io/tidb/bigdata/tidb/JdbcConnectionProviderFactory.java]: Thank you. This is really a potential problem. We should add a try-catch when registering the JDBC driver.  Now I have corrected it and you can check the newest commit.

File: tidb/src/main/java/io/tidb/bigdata/tidb/JdbcConnectionProviderFactory.java (hunk 3 above)
Comment (Daemonxiao) [reply tidb/src/main/java/io/tidb/bigdata/tidb/JdbcConnectionProviderFactory.java:34]: You can find the purpose at this [link](https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-usagenotes-connect-drivermanager.html).

File: tidb/src/main/java/io/tidb/bigdata/tidb/JdbcConnectionProviderFactory.java (hunk 1 above)
Comment (Daemonxiao) [reply tidb/src/main/java/io/tidb/bigdata/tidb/JdbcConnectionProviderFactory.java]: yeah, That is confusing. I add a link to `com.mysql.cj.jdbc.Driver`.

**Review by xuanyu66 — APPROVED** [review]

**Review by shiyuhang0 — APPROVED** [review]

File: tidb/src/main/java/io/tidb/bigdata/tidb/ClientConfig.java [hunk 5]
```diff
@@ -25,7 +25,7 @@ public final class ClientConfig {
 
   public static final String TIDB_DRIVER_NAME = "io.tidb.bigdata.jdbc.TiDBDriver";
```
Comment (humengyu2012) [inline tidb/src/main/java/io/tidb/bigdata/tidb/ClientConfig.java:26]: It's not used. Maybe we should delete it.

File: tidb/src/main/java/io/tidb/bigdata/tidb/ClientConfig.java [hunk 6]
```diff
@@ -25,7 +25,7 @@ public final class ClientConfig {
...
 
-  public static final String MYSQL_DRIVER_NAME = "com.mysql.jdbc.Driver";
+  public static final String MYSQL_DRIVER_NAME = "com.mysql.cj.jdbc.Driver";
```
Comment (humengyu2012) [inline tidb/src/main/java/io/tidb/bigdata/tidb/ClientConfig.java:28]: Same as above.

**Review by humengyu2012 — APPROVED** [review]
LGTM

File: tidb/src/main/java/io/tidb/bigdata/tidb/ClientConfig.java (hunk 5 above)
Comment (Daemonxiao) [reply tidb/src/main/java/io/tidb/bigdata/tidb/ClientConfig.java]: @humengyu2012 Thanks for your review. I have removed it.

File: tidb/src/main/java/io/tidb/bigdata/tidb/ClientConfig.java (hunk 6 above)
Comment (Daemonxiao) [reply tidb/src/main/java/io/tidb/bigdata/tidb/ClientConfig.java]: Well, I have already removed it.
