### PR TITLE
[Issue-199] Fix upsert bug

### LINKED ISSUE #199: [BUG] TIKV sink's upsert bug
## Version
- TiBigData Flink 1.14
- TiDB v6.0.0
- TiCDC v6.0.0
- Kafka 2.13-3.2.0

## Bug 
1. create table
```
CREATE TABLE `test`.`flink_sink`  (
  `id` bigint(20) NOT NULL,
  `name` varchar(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
);

CREATE TABLE `test`.`flink`  (
  `id` bigint(20) NOT NULL,
  `name` varchar(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
);
```
2. Use Kafka source get change log from TiCDC
3. create catalog  in sql-client and set 
   - 'tidb.sink.impl' = 'TiKV'
   - 'tikv.sink.buffer-size' = '1'
   - 'tidb.write_mode'='upsert'
```
CREATE CATALOG `tidb` WITH (   'type' = 'tidb',   'tidb.database.url' = 'jdbc:mysql://127.0.0.1:4000?useSSL=false',   'tidb.username' = 'root',   'tidb.password' = '',   'tidb.streaming.source' = 'kafka',   'tidb.streaming.codec' = 'json',   'tidb.streaming.kafka.bootstrap.servers' = 'localhost:9092',   'tidb.streaming.kafka.topic' = 'cdc',   'tidb.streaming.kafka.group.id' = 'test_cdc_group',   'tidb.streaming.ignore-parse-errors' = 'true' ,'tidb.sink.impl'='TIKV','tikv.sink.buffer-size'='1','tidb.write_mode'='upsert')
```
4. execute SQL in flink sql-client 
```
INSERT INTO `tidb`.`test`.`flink_sink` SELECT id,name FROM `tidb`.`test`.`flink`
```
6. Use JDBC to insert data into flink_sink
```
INSERT into test.flink_sink VALUES (1,1)
```
7. Use JDBC to insert data into flink
```
INSERT into test.flink VALUES (1,1_update)
```
8. check flink_sink: (1,1) will be deleted rather than upsert

### PR DESCRIPTION
**Pull request by xuanyu66**
## What is the purpose of the change

close #199

When BytePair has the same key, it seems like the executive order is not the same as the list order.
When upserting, there are two pairs, one is for the delete(value='') and another is for the insert(value='newValue').
In this situation, we should remove the delete and keep the insert(since it's a KV store, we can update the value).

## Brief change log

- cache the delete pairs for the row, remove if there is an insert pair that has the same key.

## Verifying this change

This change added tests and can be verified as follows:
- `TiKVUpsertTest#testUpsert()`

## Does this pull request potentially affect one of the following parts:

- Dependencies (does it add or upgrade a dependency): (no)
- The public API: (no)
- The runtime per-record code paths (performance sensitive): (no)

## Documentation

- Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Review by shiyuhang0 — APPROVED** [review]

**Review by zhangyangyu — APPROVED** [review]

File: tidb/src/main/java/io/tidb/bigdata/tidb/codec/TiDBEncodeHelper.java [hunk 1]
```diff
@@ -320,10 +325,13 @@ public List<BytePairWrapper> generateKeyValuesByRow(Row row) {
     keyValues.add(generateRecordKeyValue(row, handle, false));
     keyValues.addAll(generateIndexKeyValues(row, handle, false));
 
+    // if the key needs to be updated, then the deletion pair need to be removed and keep
+    // the update pair. Otherwise, the execution order can't be guaranteed, which may cause
+    // a problem when the update pair is executed first.
```
Comment (Daemonxiao) [inline tidb/src/main/java/io/tidb/bigdata/tidb/codec/TiDBEncodeHelper.java:330]: how about explaining what's problem would be caused? such as ".. may cause the key-value delete when the... and delete pair is executed second".
