### PR TITLE
Fix the bug when the value of unique index is NULL

### LINKED ISSUE #213: [BUG] deduplicate with null unique key
**Describe the bug**

TiBigData insert with a row with null unique key has unexpected results

## MINIBATCH

**What did you do**

```
  private static final String TABLE =
      "CREATE TABLE IF NOT EXISTS `%s`.`%s`\n"
          + "("
          + "  `id` bigint(20),\n"
          + "  `name` varchar(255) primary Key CLUSTERED,\n"
          + "  `age` int(11) NULL DEFAULT NULL,\n"
          + "  unique key(`id`)"
          + ")";

  public void testUpsert() throws Exception {
    EnvironmentSettings settings = EnvironmentSettings.newInstance().inBatchMode().build();
    StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();
    env.setParallelism(1);
    TableEnvironment tableEnvironment = StreamTableEnvironment.create(env, settings);
    String dstTable = RandomUtils.randomString();
    Map<String, String> properties = defaultProperties();
    properties.put(SINK_IMPL.key(), TIKV.name());
    properties.put(SINK_TRANSACTION.key(), SinkTransaction.MINIBATCH.name();
    properties.put(WRITE_MODE.key(), "upsert");
    TiDBCatalog tiDBCatalog = initTiDBCatalog(dstTable, TABLE, tableEnvironment, properties);

    tableEnvironment.sqlUpdate(
        String.format(
            "INSERT INTO `tidb`.`%s`.`%s` " + "VALUES(cast(null as int), 'before', 1), (cast(null as int), 'before', 1)",
            DATABASE_NAME, dstTable));
    tableEnvironment.execute("test");
}
```

**What do you expect**

Null should not equal null, no exception should be thrown

**What happens instead**

image
image

## Global

**What did you do**

```
  private static final String TABLE =
      "CREATE TABLE IF NOT EXISTS `%s`.`%s`\n"
          + "("
          + "  `id` bigint(20),\n"
          + "  `name` varchar(255) primary Key CLUSTERED,\n"
          + "  `age` int(11) NULL DEFAULT NULL,\n"
          + "  unique key(`id`)"
          + ")";

  public void testUpsert() throws Exception {
    EnvironmentSettings settings = EnvironmentSettings.newInstance().inBatchMode().build();
    StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();
    env.setParallelism(1);
    TableEnvironment tableEnvironment = StreamTableEnvironment.create(env, settings);
    String dstTable = RandomUtils.randomString();
    Map<String, String> properties = defaultProperties();
    properties.put(SINK_IMPL.key(), TIKV.name());
    properties.put(SINK_TRANSACTION.key(), SinkTransaction.GLOBAL.name();
    properties.put(WRITE_MODE.key(), "upsert");
    TiDBCatalog tiDBCatalog = initTiDBCatalog(dstTable, TABLE, tableEnvironment, properties);

    tableEnvironment.sqlUpdate(
        String.format(
            "INSERT INTO `tidb`.`%s`.`%s` " + "VALUES(cast(null as int), 'before', 1), (cast(null as int), 'before', 1)",
            DATABASE_NAME, dstTable));
    tableEnvironment.execute("test");
}
```

**What do you expect**

Null should not equal null, no exception should be thrown

**What happens instead**

image
```
  @Override
  public void processElement(
      Row row, KeyedProcessFunction<List<Object>, Row, Row>.Context ctx, Collector<Row> out)
      throws Exception {
    if (existState.value() == null) {
      existState.update(true);
      out.collect(row);
    } else if (!sinkOptions.isDeduplicate()) {
      String names = String.join(", ", uniqueIndexColumnNames);
      String values =
	//Object::toString throw java.lang.NullPointerException
          ctx.getCurrentKey().stream().map(Object::toString).collect(Collectors.joining(", "));
      throw new IllegalStateException(
          String.format(
              "Duplicate index in one batch, please enable deduplicate, index: [%s] = [%s]",
              names, values));
    }
  }
```

### PR DESCRIPTION
**Pull request by xuanyu66**
## What is the purpose of the change

close #213 

## Brief change log

- If the current Key contains NULL when processing elements in `KeyedProcessFunction`, collect the row directly without the duplication check.
- If the indexValue contains NULL when adding row into `DeduplicateRowBuffer`, add the row directly.
- move `DeduplicateRowBuffer` and `RowBuffer` to the package buffer.

## Verifying this change

This change added tests and can be verified as follows:
- TiKVDeduplicateNullableIndexTest#testDeduplicateWithNullUniqueIndex()

## Does this pull request potentially affect one of the following parts:

- Dependencies (does it add or upgrade a dependency): (no)
- The public API: (no)
- The runtime per-record code paths (performance sensitive): (no)

## Documentation

- Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Comment by xuanyu66** [comment]
@shiyuhang0 @humengyu2012 @zhangyangyu @Daemonxiao  PTAL

**Review by zhangyangyu — APPROVED** [review]

File: tidb/src/main/java/io/tidb/bigdata/tidb/buffer/DeduplicateRowBuffer.java [hunk 1]
```diff
@@ -63,11 +65,18 @@ public boolean add(Row row) {
               indexColumns.stream()
                   .map(i -> row.get(i.getOffset(), null))
                   .collect(Collectors.toList()));
+
+      // Since NULL != NULL, we don't deduplicate key with NULL.
+      if (indexValue.contains(null)) {
+        rows.add(row);
+        return true;
+      }
```
Comment (shiyuhang0) [inline tidb/src/main/java/io/tidb/bigdata/tidb/buffer/DeduplicateRowBuffer.java:73]: we need to continue rather than add row and return true.
because indexValue.contains(null) only shows this uniqueIndex has no conflict, we also need to check another uniqueIndex in next loop

File: flink/flink-1.14/src/test/java/io/tidb/bigdata/flink/tidb/sink/TiKVDeduplicateNullableIndexTest.java [hunk 2]
```diff
@@ -0,0 +1,108 @@
...
+    properties.put(DEDUPLICATE.key(), Boolean.toString(deduplicate));
+    properties.put(WRITE_MODE.key(), writeMode.name());
+
+    TiDBCatalog tiDBCatalog =
+        initTiDBCatalog(dstTable, TABLE_UK_NULLABLE, tableEnvironment, properties);
+
+    tableEnvironment.sqlUpdate(
+        String.format(
+            "INSERT INTO `tidb`.`%s`.`%s` "
+                + "VALUES(1, cast(null as int)), (2, cast(null as int))",
```
Comment (Daemonxiao) [inline flink/flink-1.14/src/test/java/io/tidb/bigdata/flink/tidb/sink/TiKVDeduplicateNullableIndexTest.java]: What should happen here if SQL is "`VALUES(cast(null as int),  10), (cast(null as int), 20)`"  and `id` is not the `primary key`?

Comment (Daemonxiao) [reply flink/flink-1.14/src/test/java/io/tidb/bigdata/flink/tidb/sink/TiKVDeduplicateNullableIndexTest.java]: I have gotten the result in the new commit. Plz, click resolve this comment.

**Review by shiyuhang0 — APPROVED** [review]

**Review by Daemonxiao — APPROVED** [review]

**Review by humengyu2012 — APPROVED** [review]
LGTM
